#! /usr/bin/env ruby

require 'rubygems'
require 'nokogiri'
require 'open-uri'

def emails_valdoise()
	scrap_stockage = Hash.new(0)

	page_val_doise = Nokogiri::HTML(open("http://annuaire-des-mairies.com/val-d-oise.html"))
	ndd = "http://annuaire-des-mairies.com"

	page_val_doise.css('a.lientxt').each do |ancre_ville|
		ziurl = ndd + ancre_ville["href"]
		zimail = emails_valdoise(ziurl)
		scrap_stockage[ancre_ville.text] = zimail
	end

	puts scrap_stockage
end


def scrap_emails(scrap_url)
	contenu_a_scrap = Nokogiri::HTML(open(scrap_url))
	email_addresses = contenu_a_scrap.css('p.Style22')[11].text
	return email_addresses
end

url_95()


def get_all_the_emails_of_val_doise_townhalls
	scrapetown = Nokogiri::HTML(open("http://annuaire-des-mairies.com/val-d-oise.html"))

	scrapetown.css('a.lientxt').each do |chose|

		stockage = Hash.new
		urlgot = ndd + chose ["href"]
		villegot = chose.text

		stockage[:"#{villegot}"] = "#{urlgot}"
		stockage[:test] = 10
		puts urlgot
	end
end

puts get_all_the_emails_of_val_doise_townhalls
=end
